[project]
name = 'Community-Weather-Oracle'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.hyper-local-data-marketplace]
path = 'contracts/hyper-local-data-marketplace.clar'
clarity_version = 3
epoch = 'latest'

[contracts.prediction-accuracy-scoring]
path = 'contracts/prediction-accuracy-scoring.clar'
clarity_version = 3
epoch = '3.2'

[contracts.weather-sensor-incentives]
path = 'contracts/weather-sensor-incentives.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
